# RSAI Model Configuration

# Model parameters
model:
  name: "RSAI"
  version: "1.0.0"
  
  # Stratification parameters
  stratification:
    method: "quantile"  # Options: quantile, kmeans, custom
    n_strata: 10
    min_samples_per_stratum: 30
    
  # Time parameters
  time:
    frequency: "monthly"  # Options: daily, weekly, monthly, quarterly
    rolling_window: 12
    min_periods: 6
    
  # Feature parameters
  features:
    property_characteristics:
      - "living_area"
      - "bedrooms"
      - "bathrooms"
      - "age"
      - "lot_size"
    location_features:
      - "zip_code"
      - "county"
      - "msa"
    temporal_features:
      - "month"
      - "quarter"
      - "year"
      
# Data parameters
data:
  # Input data format
  input_format: "parquet"  # Options: parquet, csv, feather
  
  # Column mappings
  columns:
    price: "sale_price"
    date: "sale_date"
    property_id: "property_id"
    
  # Data quality thresholds
  quality:
    min_price: 10000
    max_price: 10000000
    max_missing_ratio: 0.1
    
# Preprocessing parameters
preprocessing:
  # Outlier detection
  outliers:
    method: "iqr"  # Options: iqr, zscore, isolation_forest
    iqr_multiplier: 1.5
    zscore_threshold: 3.0
    
  # Missing value handling
  missing_values:
    numeric_strategy: "median"  # Options: mean, median, mode, drop
    categorical_strategy: "mode"  # Options: mode, constant, drop
    
  # Feature scaling
  scaling:
    method: "robust"  # Options: standard, minmax, robust
    
# Training parameters
training:
  # Cross-validation
  cv:
    method: "time_series_split"  # Options: kfold, time_series_split
    n_splits: 5
    
  # Optimization
  optimization:
    metric: "rmse"  # Options: rmse, mae, mape, r2
    direction: "minimize"
    
# Evaluation parameters
evaluation:
  metrics:
    - "rmse"
    - "mae"
    - "mape"
    - "r2"
  backtesting:
    enabled: true
    test_size: 0.2
    
# Output parameters
output:
  # Results format
  format: "parquet"  # Options: parquet, csv, json
  
  # Paths
  paths:
    models: "models/saved"
    predictions: "output/predictions"
    indices: "output/indices"
    reports: "output/reports"
    
# Logging parameters
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR
  format: "json"  # Options: json, text
  file: "logs/rsai.log"
  
# Performance parameters
performance:
  # Polars optimization
  polars:
    streaming: false
    lazy_evaluation: true
    n_threads: null  # null = use all available
    
  # Memory management
  memory:
    chunk_size: 100000
    max_memory_gb: 16